services:
  - type: worker
    name: dhaniya-sir
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: node --unhandled-rejections=strict dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: TOKEN
        sync: false
      - key: CLIENT_ID
        sync: false
      - key: openrouter_api
        sync: false
      - key: system_prompt
        sync: false